create INDEX USERSTATISTIC_LOCATION_IDX ON USERSTATISTIC(LOCATION) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
DROP INDEX TRAJECTORY_IDX;

DESCRIBE USER_SDO_GEOM_METADATA;
select * from USER_SDO_GEOM_METADATA;
DELETE from USER_SDO_GEOM_METADATA where table_name='TRAJECTORY';

select * from ICAMPUS.USERS;
select * from ICAMPUS.FACEBOOK;

select * from userstatistic where userid = 1646143197
select * from user_preferences where user_id = 1646143197



delete from ICAMPUS.USERS;
delete from ICAMPUS.FACEBOOK;


  CREATE TABLE "HIENTT"."USERSTATISTIC" 
   (	
        "ID" NUMBER,
        "SESSIONID" NUMBER, 
	"USERID" NUMBER, 
	"TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
        "LOCATION" "SDO_GEOMETRY"
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
 create trigger "HIENTT"."USERSTATISTIC_AUTO_INCREMENT"
before insert on "HIENTT"."USERSTATISTIC"  
for each row
begin
select SEQ_1000.nextval into :NEW."USERSTATISTIC" from dual;
end;

CREATE OR REPLACE TRIGGER "HIENTT"."USERSTATISTIC_AUTO_INCREMENT"
BEFORE INSERT
ON "HIENTT"."USERSTATISTIC"
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT USERSTATISTIC_SEQUENCE.nextval INTO :NEW.ID FROM dual;
END;
 


  CREATE OR REPLACE TRIGGER "HIENTT"."SESSIONID_AUTO_INCREMENT" before insert on "HIENTT"."USERSTATISTIC"    for each row begin     if inserting then       if :NEW."SESSIONID" is null then          select SEQ_1000.nextval into :NEW."SESSIONID" from dual;       end if;    end if; end;
/

ALTER TRIGGER "HIENTT"."USERSTATISTIC_AUTO_INCREMENT" ENABLE;
ALTER TRIGGER "HIENTT"."SESSIONID_AUTO_INCREMENT" ENABLE;

drop trigger "HIENTT"."SESSIONID_AUTO_INCREMENT";
drop trigger "HIENTT"."USERSTATISTIC_AUTO_INCREMENT";

CREATE SEQUENCE USERSTATISTIC_SEQUENCE
START WITH 1
INCREMENT BY 1;

